### ISSUE TITLE
AWS Server

### ISSUE THREAD

**Issue by harinath101515** [yisol/IDM-VTON#62]
It is possible to run on AWS server

**Comment by theguaz** [comment]
I'm running it on a **g5.8xlarge** right now

**Comment by harinath101515** [comment]
> I'm running it on a **g5.8xlarge** right now

are you using the git hub repository or you paid for the membership

**Comment by theguaz** [comment]
I just launched a g5 instance on my personal AWS account, then logged in using SSH and used it as any other computer, costs are not cheap tho.

**Comment by harinath101515** [comment]
> I'm running it on a **g5.8xlarge** right now

i am talking about source code which source code you are using , are you using git hub source code or your brought 1 click installer scripts from https://www.patreon.com/ this website

**Comment by theguaz** [comment]
this exact repo, ny steps where like this;


Step 1: Clone the repository
git clone https://github.com/yisol/IDM-VTON

Step 2: Navigate inside the cloned repository
cd IDM-VTON

Step 3: Create virtual environment ( conda or venv)

Step 4: Activate virtual environment ( conda or venv)

Step 5: Install requirements using the yaml file, and also onnxruntime fpr Linux in my case

Step 6: Download checkpoints

1. IDM-VTON\ckpt\densepose
	https://huggingface.co/yisol/IDM-VTON/tree/main/densepose

2. IDM-VTON\ckpt\humanparsing (parsing_atr.onnx and parsing_lip.onnx)
	https://huggingface.co/levihsu/OOTDiffusion/tree/main/checkpoints/humanparsing

3. IDM-VTON\ckpt\openpose\ckpts
	https://huggingface.co/lllyasviel/ControlNet/blob/main/annotator/ckpts/body_pose_model.pth


Step 7: Download VTON models
mkdir yisol
cd yisol
git lfs install
git clone https://huggingface.co/yisol/IDM-VTON

Step 8: Launch the gradio UI
venv\scripts\activate
python gradio_demo/app.py

**Comment by harinath101515** [comment]
I need to try these all steps in aws g5 

> this exact repo, ny steps where like this;
> 
> **Step 1: Clone the repository** git clone https://github.com/yisol/IDM-VTON
> 
> **Step 2: Navigate inside the cloned repository** cd IDM-VTON
> 
> **Step 3: Create virtual environment ( conda or venv)**
> 
> **Step 4: Activate virtual environment ( conda or venv)**
> 
> **Step 5: Install requirements using the yaml file, and also onnxruntime fpr Linux in my case**
> 
> **Step 6: Download checkpoints**
> 
> 1. IDM-VTON\ckpt\densepose
>    https://huggingface.co/yisol/IDM-VTON/tree/main/densepose
> 2. IDM-VTON\ckpt\humanparsing (parsing_atr.onnx and parsing_lip.onnx)
>    https://huggingface.co/levihsu/OOTDiffusion/tree/main/checkpoints/humanparsing
> 3. IDM-VTON\ckpt\openpose\ckpts
>    https://huggingface.co/lllyasviel/ControlNet/blob/main/annotator/ckpts/body_pose_model.pth
> 
> **Step 7: Download VTON models** mkdir yisol cd yisol git lfs install git clone https://huggingface.co/yisol/IDM-VTON
> 
> **Step 8: Launch the gradio UI** venv\scripts\activate python gradio_demo/app.py

if i try these steps in aws g5 is it working

**Comment by brenogibson** [comment]
Hi, I've done this and could execute using "accelerate launch inference.py". Can you guys help me get it working for a single image of mine? I want to make an app to capture from my webcam and put the clothes on me

**Comment by harinath101515** [comment]
Can you explain how to execute code in cloud.

**Comment by FurkanGozukara** [comment]
i have a full cloud tutorial may help you : https://youtu.be/LeHfgq_lAXU

**Comment by nitinmukesh** [comment]
> g5.8xlarge

I just checked the price. You could buy a very high end PC at that price. Unable to understand why are you paying such huge price?

**Comment by brenogibson** [comment]
> > g5.8xlarge
> 
> I just checked the price. You could buy a very high end PC at that price. Unable to understand why are you paying such huge price?
> 
> 2500 dollars for 1 hour https://instances.vantage.sh/aws/ec2/g5.8xlarge?region=us-east-1&os=linux&cost_duration=hourly&reserved_term=Standard.noUpfront

It is 2,5 USD per hour, not 2 thousand

**Comment by yaghya** [comment]
> this exact repo, ny steps where like this;
> 
> **Step 1: Clone the repository** git clone https://github.com/yisol/IDM-VTON
> 
> **Step 2: Navigate inside the cloned repository** cd IDM-VTON
> 
> **Step 3: Create virtual environment ( conda or venv)**
> 
> **Step 4: Activate virtual environment ( conda or venv)**
> 
> **Step 5: Install requirements using the yaml file, and also onnxruntime fpr Linux in my case**
> 
> **Step 6: Download checkpoints**
> 
> 1. IDM-VTON\ckpt\densepose
>    https://huggingface.co/yisol/IDM-VTON/tree/main/densepose
> 2. IDM-VTON\ckpt\humanparsing (parsing_atr.onnx and parsing_lip.onnx)
>    https://huggingface.co/levihsu/OOTDiffusion/tree/main/checkpoints/humanparsing
> 3. IDM-VTON\ckpt\openpose\ckpts
>    https://huggingface.co/lllyasviel/ControlNet/blob/main/annotator/ckpts/body_pose_model.pth
> 
> **Step 7: Download VTON models** mkdir yisol cd yisol git lfs install git clone https://huggingface.co/yisol/IDM-VTON
> 
> **Step 8: Launch the gradio UI** venv\scripts\activate python gradio_demo/app.py

After following these steps , I am getting this error

ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/opt/conda/envs/idm/lib/python3.10/site-packages/pydantic/type_adapter.py", line 270, in _init_core_attrs
    self._core_schema = _getattr_no_parents(self._type, '__pydantic_core_schema__')
  File "/opt/conda/envs/idm/lib/python3.10/site-packages/pydantic/type_adapter.py", line 112, in _getattr_no_parents
    raise AttributeError(attribute)
AttributeError: __pydantic_core_schema__

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/idm/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/opt/conda/envs/idm/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/opt/conda/envs/idm/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/conda/envs/idm/lib/python3.10/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/conda/envs/idm/lib/python3.10/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/opt/conda/envs/idm/lib/python3.10/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/opt/conda/envs/idm/lib/python3.10/site-packages/gradio/route_utils.py", line 686, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/opt/conda/envs/idm/lib/python3.10/site-packages/gradio/route_utils.py", line 702, in simple_response
    await self.app(scope, receive, send)
  File "/opt/conda/envs/idm/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/opt/conda/envs/idm/lib/python3.10/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/opt/conda/envs/idm/lib/python3.10/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/opt/conda/envs/idm/lib/python3.10/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/conda/envs/idm/lib/python3.10/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/opt/conda/envs/idm/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/opt/conda/envs/idm/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/opt/conda/envs/idm/lib/python3.10/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/opt/conda/envs/idm/lib/python3.10/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/opt/conda/envs/idm/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/opt/conda/envs/idm/lib/python3.10/site-packages/fastapi/routing.py", line 291, in app
    solved_result = await solve_dependencies(
  File "/opt/conda/envs/idm/lib/python3.10/site-packages/fastapi/dependencies/utils.py", line 656, in solve_dependencies
    ) = await request_body_to_args(  # body_params checked above
  File "/opt/conda/envs/idm/lib/python3.10/site-packages/fastapi/dependencies/utils.py", line 881, in request_body_to_args
    fields_to_extract = get_cached_model_fields(first_field.type_)
  File "/opt/conda/envs/idm/lib/python3.10/site-packages/fastapi/_compat.py", line 657, in get_cached_model_fields
    return get_model_fields(model)
  File "/opt/conda/envs/idm/lib/python3.10/site-packages/fastapi/_compat.py", line 284, in get_model_fields
    return [
  File "/opt/conda/envs/idm/lib/python3.10/site-packages/fastapi/_compat.py", line 285, in <listcomp>
    ModelField(field_info=field_info, name=name)
  File "<string>", line 6, in __init__
  File "/opt/conda/envs/idm/lib/python3.10/site-packages/fastapi/_compat.py", line 110, in __post_init__
    self._type_adapter: TypeAdapter[Any] = TypeAdapter(
  File "/opt/conda/envs/idm/lib/python3.10/site-packages/pydantic/type_adapter.py", line 257, in __init__
    self._init_core_attrs(rebuild_mocks=False)
  File "/opt/conda/envs/idm/lib/python3.10/site-packages/pydantic/type_adapter.py", line 135, in wrapped
    return func(self, *args, **kwargs)
  File "/opt/conda/envs/idm/lib/python3.10/site-packages/pydantic/type_adapter.py", line 277, in _init_core_attrs
    self._core_schema = _get_schema(self._type, config_wrapper, parent_depth=self._parent_depth)
  File "/opt/conda/envs/idm/lib/python3.10/site-packages/pydantic/type_adapter.py", line 95, in _get_schema
    schema = gen.generate_schema(type_)
  File "/opt/conda/envs/idm/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 655, in generate_schema
    schema = self._generate_schema_inner(obj)
  File "/opt/conda/envs/idm/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 908, in _generate_schema_inner
    return self._annotated_schema(obj)
  File "/opt/conda/envs/idm/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 2028, in _annotated_schema
    schema = self._apply_annotations(source_type, annotations)
  File "/opt/conda/envs/idm/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 2107, in _apply_annotations
    schema = get_inner_schema(source_type)
  File "/opt/conda/envs/idm/lib/python3.10/site-packages/pydantic/_internal/_schema_generation_shared.py", line 83, in __call__
    schema = self._handler(source_type)
  File "/opt/conda/envs/idm/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 2189, in new_handler
    schema = metadata_get_schema(source, get_inner_schema)
  File "/opt/conda/envs/idm/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 2185, in <lambda>
    lambda source, handler: handler(source)
  File "/opt/conda/envs/idm/lib/python3.10/site-packages/pydantic/_internal/_schema_generation_shared.py", line 83, in __call__
    schema = self._handler(source_type)
  File "/opt/conda/envs/idm/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 2088, in inner_handler
    schema = self._generate_schema_inner(obj)
  File "/opt/conda/envs/idm/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 929, in _generate_schema_inner
    return self.match_type(obj)
  File "/opt/conda/envs/idm/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 1029, in match_type
    return self._match_generic_type(obj, origin)
  File "/opt/conda/envs/idm/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 1058, in _match_generic_type
    return self._union_schema(obj)
  File "/opt/conda/envs/idm/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 1378, in _union_schema
    choices.append(self.generate_schema(arg))
  File "/opt/conda/envs/idm/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 655, in generate_schema
    schema = self._generate_schema_inner(obj)
  File "/opt/conda/envs/idm/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 929, in _generate_schema_inner
    return self.match_type(obj)
  File "/opt/conda/envs/idm/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 1038, in match_type
    return self._unknown_type_schema(obj)
  File "/opt/conda/envs/idm/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 558, in _unknown_type_schema
    raise PydanticSchemaGenerationError(
pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class 'starlette.requests.Request'>. Set arbitrary_types_allowed=True in the model_config to ignore this error or implement __get_pydantic_core_schema__ on your type to fully support it.

If you got this error by calling handler(<some type>) within __get_pydantic_core_schema__ then you likely need to call handler.generate_schema(<some type>) since we do not call __get_pydantic_core_schema__ on <some type> otherwise to avoid infinite recursion.
