### ISSUE TITLE
OSError: IDM-VTON does not appear to have a file named config.json.

### ISSUE THREAD

**Issue by boy-wei** [yisol/IDM-VTON#74]
Traceback (most recent call last):
  File "D:\file\OOTDiffusion-main\IDM-VTON-main\gradio_demo\app.py", line 49, in <module>
    unet = UNet2DConditionModel.from_pretrained(
  File "D:\py\Anaconda3\envs\ootd\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "D:\py\Anaconda3\envs\ootd\lib\site-packages\diffusers\models\modeling_utils.py", line 712, in from_pretrained
    config, unused_kwargs, commit_hash = cls.load_config(
  File "D:\py\Anaconda3\envs\ootd\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "D:\py\Anaconda3\envs\ootd\lib\site-packages\diffusers\configuration_utils.py", line 402, in load_config
    raise EnvironmentError(
OSError: IDM-VTON does not appear to have a file named config.json.

**Comment by bobgus39** [comment]
I have the same problem and it's so difficult installing it on windows and running in local

**Comment by FurkanGozukara** [comment]
I have this tutorial to install 1 click on Windows

https://youtu.be/m4pcIeAVQD0?si=GNoQxErebteP8iss

**Comment by nitinmukesh** [comment]
@boy-wei @bobgus39 

Please refer this tutorial
https://youtu.be/aQAuFleb2Gs

**Comment by hothot9532** [comment]
@boy-wei @bobgus39

Have you solved this problem? I am also facing the same issue.

**Comment by bobgus39** [comment]
@boy-wei @hothot9532 @nitinmukesh 

> You need to rename the downloaded config file as it prepend the folder name in file name.
> 
> 
> 
> Please refer this tutorial
> 
> https://youtu.be/aQAuFleb2Gs

That video is perfect, my mistake was the env of Python 

And I recommend @FurkanGozukara 's patreon, he has helped me a lot
