### ISSUE TITLE
whole body image success, half body image failed?

### ISSUE THREAD

**Issue by Nomination-NRB** [yisol/IDM-VTON#79]
We tried to use a half picture to try on the clothes, but found an error(whole body image success).
half image:
![image](https://github.com/yisol/IDM-VTON/assets/83486284/8e6d8205-34bd-44c1-a840-ee150120c584)

whole image:
![attach_result](https://github.com/yisol/IDM-VTON/assets/83486284/c1cf90d2-13bf-4bb7-aed6-e99a3d6d5418)

Console output:

init_image.shape => torch.Size([1, 4, 1024, 768])
Traceback (most recent call last):
  File "/home/huishi/workspace/data/repository/IDM-VTON/gradio_demo/nrb.py", line 20, in <module>
    output, mask_gray = app.start_tryon(imgs, mask, garm_img, prompt, is_checked, is_checked_crop, denoise_steps, seed)
  File "/home/huishi/workspace/data/repository/IDM-VTON/gradio_demo/app.py", line 362, in start_tryon
    images = pipe(
  File "/home/huishi/anaconda3/envs/idm/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/huishi/workspace/data/repository/IDM-VTON/./src/tryon_pipeline.py", line 1637, in __call__
    mask, masked_image_latents = self.prepare_mask_latents(
  File "/home/huishi/workspace/data/repository/IDM-VTON/./src/tryon_pipeline.py", line 955, in prepare_mask_latents
    my_masked_image = (masked_image.detach().cpu().squeeze().permute(1, 2, 0).numpy() * 255).astype(np.uint8)
AttributeError: 'NoneType' object has no attribute 'detach'

We found that the code locate in IDM-VTON/src/tryon_pipeline.py:
```python
print(f'1598 init_image.shape => {init_image.shape}')
if masked_image_latents is not None:
    print(1600)
    masked_image = masked_image_latents
elif init_image.shape[1] == 4:
    # if images are in latent space, we can't mask it
    print(1602)
    print(f'init_image.shape => {init_image.shape}')
    masked_image = None
else:
    print(1607)
    masked_image = init_image * (mask < 0.5)
```

If we change another image(whole body), we will get `1598 init_image.shape => torch.Size([1, 3, 1024, 768])`, it is correct, but we don't know what does it mean: # if images are in latent space, we can't mask it

**Comment by Nomination-NRB** [comment]
There is a problem with the tool of clipping pictures used before, and the code runs after clipping pictures using cv2
